
networks:
  nat-net:
    external: false

services:
  image_creator:
    build:
      context: .
    volumes:
      - ./files/entry.sh:/entry.sh
      - ./files/prepare_image.sh:/usr/local/bin/prepare_image.sh

      - ./iso:/iso
      - ./files/system:/system

    networks:
      - nat-net

    privileged: true
    cap_add: ['ALL']
    devices:
      - /dev/fuse

