#!/bin/sh


[ -n "$PRETEND" ] && [[ $(echo "$PRETEND" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] && \
        RUN="echo" || RUN=

[ -n "$DEBUG" ] && [[ $(echo "$DEBUG" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] && \
        set -xe || set -e


function first_arg() {
  echo $1
}

function second_arg() {
  echo $2
}

function last_args() {
  if [ -n "$1" ]; then
    shift
  fi

  echo "$@"
}

readonly ONE_MIB=$(( 1024 * 1024 ))
readonly ONE_GIB=$(( 1024 * $ONE_MIB ))

readonly BOOT_FS_OFFSET=$(( 8192 * 512 ))

declare -A devices_dtb
declare -A devices_cpu

# arm:
devices_dtb["raspi0"]="alpine-standard/bcm2835-rpi-zero.dtb"
devices_cpu["raspi0"]="arm1176"

# aarch:
devices_dtb["raspi3b"]="raspios-bookworm-arm64/bcm2710-rpi-3-b.dtb"
devices_cpu["raspi3b"]="cortex-a53"


readonly BOOT_MNT_DIR="/mnt/img.boot"

readonly AWSTORE_DIR="/var/lib/alphawrap"
readonly DTB_LIB="/var/lib/alphawrap/_dtb"
readonly DB_DIR="/var/lib/alphawrap/_db"

readonly EXTSTORE_DIR="/var/lib/alphawrap/ext_storage"
readonly TEMP_DIR="/var/tmp"

readonly LOCK_FILE="/tmp/alpha_wrap-run.lock"

readonly SHARE_SPACE_FILE=${AWSTORE_DIR}/__share_space.iso
readonly SHARE_SPACE_SIZE_MIB=100

readonly QEMU_MONITOR_UNIXSOCKET="/tmp/qemu-monitor"

readonly DEFAULT_DEVICE_MODEL="raspi3b"

# Global variables:
# From parameters:
_MODE=

_IMG_BOOT=0
_NO_PART_TABLE_MODE=-1

_DEV_MODEL=${DEFAULT_DEVICE_MODEL}
_MACHINE=$_DEV_MODEL

_IMG_FILE=
_KERNEL=vmlinuz
_INITRAMFS=

_PERMANENT_CONTAINER=0
_CONTAINER_NAME=

_LIST_WITH_DETAILS=0

# Run-time globals
_LOBOOT_DEV=

# connection:
SSH_GUEST_PORT=15022
SSH_DEF_PRIV_KEY_NAME=id_ed25519

CONTAINER_SSH_KEY_PATH=

function print_help() {
    cat <<EOF
Usage:
Creating container:
$(basename $0) --device|-d [raspi3b] <img file> --imgboot|-i y|n <kernel> <initramfs> --name|-n <name>

  --device|-d      - Model of the emulated device (default: '${DEFAULT_DEVICE_MODEL}').
  <img file>       - Path to image file to be mounted as 'mmcblk0'.
  --imgboot|-i y|n - If 'y' load <kernel> and <initramfs> from a boot
                     partition of the image file.
                     If 'n' load <kernel> and <initramfs> from file.
                     <kernel>    - Path to kernel, if '-i y' path within
                                   boot partition of the image file.
                                   If '-i n' path to kernel file that is
                                   located at host.
                     <initramfs> - Path to initramfs, if '-i y' path within
                                   boot partition of the image file.
                                   If '-i n' path to initramfs file that is
                                   located at host.
                     Initramfs is optional, if not provided emulated system
                     will boot with just kernel image. It means that kernel
                     must have all modules to mount root fs as well as to
                     access necessary devices such as disk controller.

                     Also, <kernel> path might be skiped, in this case default
                     '${_KERNEL}' is loaded from boot image file partition
                     (if '-i y'), or current directory of a local file system
                     (if '-i n'). In this case initramfs can't be used.

  --name|-n        - Create named container, in option '-n' is followed by
                     <name> container with a given name is created.
                     If only option '-n' is provided container with random name
                     is created, name of the container is displayed upon launch.

                     If option '-n' is not provided then temporary container is
                     created - it will be removed after machine is stopped.

Launching container:
$(basename $0) <container name>
  This will launch container that has been created from an image.

Guest interaction:
$(basename $0) command <command to be exiecuted in guest>
  This will launch provided command (over SSH) in VM.

$(basename $0) sync <host source dir> [<guest target dir>]
  This will synchronize local file or directory with a location on guest
  system (over SSH). <guest target dir> can be skipped, if so default location
  is '/usr/local/bin'.

$(basename $0) enter
  Enter (ssh) to VM guest.

Listing containers:
$(basename $0) ls --full|-f
  ls - list all defined containers

Attachable (extstore) image operations:
$(basename $0) extstore [ls --full|-f] | [add <name|path> SIZE] | [eject]
  Container can have virtually attached external ("USB stick") storage.

  extstore ls  - list attachable images
    --full|-f  - list attachable images with details

  extstore add - add 'external' storage to machine, the storage will be
                 available as USB stick. Storage can be identified by a path,
                 or name. If identified by path, '$(basename $0)' is expecting
                 a file name. Indicated file will be attached to machine as a
                 storage device.
                 If name provided, '$(basename $0)' will search for an
                 attachable image in its internal storage system.

                 If storage exists, it will be attached to the machine.
                 In order to create storage, non existing image name or path
                 must be provided followed by a size. '$(basename $0)' will
                 create storage of a given size and attach it to the machine.

                 New storage is automatically initiated with zeros.
                 Default SIZE unit is MiB, SIZE can be postfixed by MiB, MB,
                 GiG, GB e.g.: 2GB

Initialization:
$(basename $0) init
  Create storage backends, databases etc. for $(basename $0)

EOF
}

# sd-card size must be of power 2, e.g.:
# 512MiB, 1GiB, 2GiB, 4GiB ...
# Append extra 'zeros' to an end of an
# image file to ensure that its size is
# exactly 2^<power> bites.
function prepare_mmc_imgfile() {
  local IMAGE_PATH="$1"
  local CACHE_FILE="$2"

  if [ ! -f "$CACHE_FILE" ] || [ ! -s "$CACHE_FILE" ] ; then
    # if file does not exists, or is a zero size copy image
    $RUN cp "$IMAGE_PATH" $CACHE_FILE
  fi
  # else, if file already exists veriry size

  CUR_SIZE=$(first_arg $(du -sb $IMAGE_PATH))

  POW=$(( 256*1024*1024 ))

  while [ $POW -lt $CUR_SIZE ]; do
    POW=$(($POW*2))
    #echo $POW
  done

  REM_SIZE_TOPOW=$(($POW - $CUR_SIZE))

  # if zero file is of a proper size already

  if [ $REM_SIZE_TOPOW -ne 0 ]; then
    #echo "Appending file with extra 'zeros' to reach size that is a power of 256 MiB (requirment for SD cards)"
    #echo "Appending by: $REM_SIZE_TOPOW bytes"
    #echo "Final size: $(($REM_SIZE_TOPOW + $CUR_SIZE)) bytes"

    # make file size to be multiple of MB:
    TAIL=$(( ($REM_SIZE_TOPOW % $ONE_MIB) ))

    # init is in bytes
    if [ $TAIL -ne 0 ]; then
      $RUN dd bs=1 seek=$CUR_SIZE if=/dev/zero of=$CACHE_FILE count=$TAIL
    fi

    # change units to MiB
    CUR_SIZE=$(( ($CUR_SIZE + $TAIL) / $ONE_MIB ))
    TAIL=$(($REM_SIZE_TOPOW / $ONE_MIB))

    if [ $TAIL -ne 0 ]; then
      $RUN dd bs=$ONE_MIB seek=$CUR_SIZE if=/dev/zero of=$CACHE_FILE count=$TAIL
    fi
  fi
}

function prepare_usbstick() {
  local PATH=$1
  local SIZE_MB=$2

  $RUN /usr/bin/dd bs=$ONE_MIB count=${SIZE_MB} if="/dev/zero" of="${PATH}"
}

function mount_boot() {
  local WORK_IMG=$1

  # Get available loop device, normally '/dev/loop0'
  if [ -z "$RUN" ]; then
    _LOBOOT_DEV=$(losetup -f)
  else
    _LOBOOT_DEV="/dev/loop0dummy"
  fi
  # Create device for mounting partition that will be used as 'boot'
  $RUN losetup $_LOBOOT_DEV $WORK_IMG
  $RUN partprobe -s $_LOBOOT_DEV

  # mount first partition, or if no partition table mount filesystem directly
  if [ -e ${_LOBOOT_DEV}p1 ]; then
    $RUN mount ${_LOBOOT_DEV}p1 $BOOT_MNT_DIR -o ro || true
    _NO_PART_TABLE_MODE=0

    if findmnt -rno TARGET "${_LOBOOT_DEV}p1" >/dev/null; then
      echo "Partition ${_LOBOOT_DEV}p1 is mounted."
    else
      echo "Falling back to mnount without partition table"
      $RUN mount ${_LOBOOT_DEV} $BOOT_MNT_DIR -o ro
      _NO_PART_TABLE_MODE=1;
    fi
  else
    $RUN mount ${_LOBOOT_DEV} $BOOT_MNT_DIR -o ro
    _NO_PART_TABLE_MODE=1
  fi
}

function umount_boot() {
  $RUN umount ${BOOT_MNT_DIR}
  $RUN losetup -d ${_LOBOOT_DEV}
}

# Check environment:
function check_environment() {
  $RUN mkdir -p ${AWSTORE_DIR} ${DB_DIR} ${TEMP_DIR} ${EXTSTORE_DIR}

  if [ ! -f "${SHARE_SPACE_FILE}" ]; then
    $RUN dd bs=${ONE_MIB} if=/dev/zero of="${SHARE_SPACE_FILE}" count=${SHARE_SPACE_SIZE_MIB}
    $RUN mkfs.ext4 -L VM.SHARE "${SHARE_SPACE_FILE}"
  fi
}

function load_containersettings() {
  if [ ! -e ${LOCK_FILE} ]; then
    echo "No running container!"

    return 1
  fi

  _CONTAINER_NAME=$(tail -n 1 ${LOCK_FILE})

  CONTAINER_SSH_KEY_PATH=${DB_DIR}/${_CONTAINER_NAME}/${SSH_DEF_KEY_NAME}

  return 0
}

# Command line parsing functions:

function set_flag_imgboot() {
  if [ -n "$2" ] && [ "yes_no" == "$2" ]; then
    _IMG_BOOT=$1
  fi
}

_VERBS="run
jump
fly
walk
sing
drive"

_NOUNS="carpet
house
river
road
mountain
car"

function set_create_container() {

  if [ -z "$2" ]; then
    if [ -z "${_CONTAINER_NAME}" ]; then
      _CONTAINER_NAME="$(echo "$_VERBS" | shuf -n 1)-$(echo "$_NOUNS" | shuf -n 1)"
    fi

    _PERMANENT_CONTAINER=1
  fi
}


function parse_yes_no() {
  if [ -z "$1" ]; then
    echo "Empty argument (fix code?)"
    exit 55
  fi

  if [[ $(echo "$1" | tr '[:upper:]' '[:lower:]') =~ ^y|yes|1|on$ ]] ; then
    return 1
  elif [[ $(echo "$1" | tr '[:upper:]' '[:lower:]') =~ ^n|no|0|off$ ]] ; then
    return 0
  else
    echo "Correct option is one of: yes, y, on, 1 or no, n, 0, off"
    exit 3
  fi
}

function parse_devmodel_name() {
  if [[ ! "$1" =~ ^([a-zA-Z0-9\._-]){1,128}$ ]]; then
    echo "Illegal machine (device) name"
    exit 3
  fi

  MACHINE=$(qemu-system-aarch64 -machine help | grep "^$1[[:space:]].*")

  if [ -z "$MACHINE" ]; then
    echo "Machine (device) has not been found: $1"
    exit 3
  fi

  _MACHINE=$(first_arg $MACHINE)
  echo "Loading: $_MACHINE"
}

function parse_kernel_name() {
  if [[ ! "$1" =~ ^([a-zA-Z0-9\._/-]){1,128}$ ]]; then
    echo "Illegal kernel name"
    exit 3
  fi

  _KERNEL=$1
}

function parse_initramfs_name() {
  if [[ ! "$1" =~ ^([a-zA-Z0-9\._/-]){1,128}$ ]]; then
    echo "Illegal initramfs name"
    exit 3
  fi

  _INITRAMFS=$1
}

function parse_imgfile_path() {
  if [ ! -f "$1" ]; then
    echo "Provide path to an existing file"
    exit 3
  fi

  _IMG_FILE=$(realpath "$1")
}

function parse_container_name() {
  if [[ ! "$1" =~ ^([_a-zA-Z0-9-]){1,128}$ ]]; then
    echo "Illegal name"
    exit 3
  fi

  _CONTAINER_NAME=$1
}

_EXTSTORAGE_MODE=
_EXTSTORAGE_REF=
_EXTSTORAGE_REF_ISINTERNAL=
_EXTSTORAGE_SIZE=

_GUEST_COMMAND=
_RSYNC_LOCAL=
_RSYNC_REMOTE=/usr/local/bin

function parse_extstorage() {
  # validation is in: set_validate_extstore_add
  _EXTSTORAGE_REF=$1
}

function parse_guestcmd() {
  _GUEST_COMMAND=$1
}

function set_guestcmd() {
  if [ -z "${_GUEST_COMMAND}" ]; then
    echo "Provide command!"
    exit 2
  fi
}

function parse_local_path() {
  _RSYNC_LOCAL=$1
}

function parse_remote_path() {
  _RSYNC_REMOTE=$1
}

function set_guestsync() {
  if [ -z "${_RSYNC_LOCAL}" ]; then
    echo "Provide file or directory name to be synchronized"
    exit 2
  fi

  if [ ! -e "${_RSYNC_LOCAL}" ]; then
    echo "File or directory does not exists!"

    exit 3
  fi
}


function parse_size() {
  local input="$1"
  local number
  local unit
  local result

  # Use regular expression to match the number and unit (MB, GB, MiB, GiB)
  if [[ "$input" =~ ^([0-9]+(\.[0-9]+)?)\ ?(MB|GB|MiB|GiB)$ ]]; then
    number="${BASH_REMATCH[1]}"
    unit="${BASH_REMATCH[3]}"

    case "$unit" in
      MB)
        result=$(echo "scale=2; $number * 0.953674" | bc)
      ;;
      GB)
        result=$(echo "scale=2; $number * 953.674" | bc)
      ;;
      MiB)
        result="$number"
      ;;
      GiB)
        result=$(echo "scale=2; $number * 1024" | bc)
      ;;
    esac

    # Round up to the nearest integer using awk
    _EXTSTORAGE_SIZE=$(echo "$result" | awk '{print ($1 == int($1)) ? $1 : int($1)+1}')
    echo "$_EXTSTORAGE_SIZE"
  else
    echo "Invalid input. Please provide a number followed by MB, GB, MiB, or GiB."
    return 1
  fi
}

function set_validate_extstore_add() {
  local FILENAME=

  if [ -n "${2}" ]; then
    # skipp "per parameter" setter call
    # proceed in the case of "finale" call (when all variables are ready)
    return
  fi

  if [[ "${_EXTSTORAGE_REF}" =~ ^[a-zA-Z0-9/\._\-]{1,1024}$ ]] ; then
    FILENAME="${_EXTSTORAGE_REF}"
    _EXTSTORAGE_REF_ISINTERNAL=0
    # probe if it's a file name:
    if [ -f "${FILENAME}" ]; then
      if [ -n "${_EXTSTORAGE_SIZE}" ]; then
        echo "Image already exists, excess size declaration, exiting"
        exit 5
      fi

      return
    fi
  fi

  if [[ "${_EXTSTORAGE_REF}" =~ ^[a-zA-Z0-9\._\-]{1,256}$ ]]; then
    FILENAME=${EXTSTORE_DIR}/${_EXTSTORAGE_REF}

    # make global variable correction (ugly)
    _EXTSTORAGE_REF="${FILENAME}"
    _EXTSTORAGE_REF_ISINTERNAL=1

    if [ -f "${FILENAME}" ]; then
      if [ -n "${_EXTSTORAGE_SIZE}" ]; then
        echo "Image already exists, excess size declaration, exiting"
        exit 5
      fi

      return
    fi
  fi

  if [ -z "${FILENAME=}" ]; then
    echo "Incorrect image file path or name"
    exit 4
  fi

  # create image if size was given:

  if [ -z "${_EXTSTORAGE_SIZE}" ]; then
    echo "No size has been provided"
    exit 4
  fi

  prepare_usbstick "${_EXTSTORAGE_REF}" ${_EXTSTORAGE_SIZE}
}

# Parser 'global' variables
# "parse_now", "param_chain" and "setter_fn" has been defined to handle
# variable parameter "chains"
# Once when 'option' has been identified such as 'ls', '--name'
# variables: 'parse_now', 'parse_chain' and 'setter_fn'
# are used to handle variable argument length parsing
# Thus, some options might be optional making command line
# more user friendly.
# parse_now is the
setter_fn=
param_chain=

# Return value:
#     1 - argument has been read
#     0 - argument can't be interpreted by current setter and parser,
#         continue parsing
function parse() {
  local opt=$1
  local _parse_now=$(first_arg $param_chain)
  local opt_param=0


  if [ -z "$_parse_now" ]; then
    return 0
  fi

  param_chain=$(last_args $param_chain)

  if [[ "${_parse_now:0:1}" == '?' ]]; then
    opt_param=1
    _parse_now="${_parse_now:1}"
  fi

  if [[ "${opt:0:1}" == "-" ]]; then
    if [ $opt_param -eq 0 ]; then
      echo "Illegal parameter (starting with '-')"
      exit 1
    else
      if [ -n "$setter_fn" ]; then
        eval "set_$setter_fn"
        setter_fn=
      fi

      _parse_now=
      param_chain=

      return 0
    fi
  fi

  if [ -n "$opt" ]; then
    eval "parse_$_parse_now \"$opt\""
    res_code=$?

    if [ -n "$setter_fn" ]; then
      eval "set_$setter_fn" $res_code $_parse_now
      #setter_fn=
    fi
  elif [ ${opt_param} -eq 0 ]; then
    if [ -n "$setter_fn" ]; then
      # setter schould terminate program as no required argument has been provided
      eval "set_$setter_fn" -1 $_parse_now
      # exited ...
    fi

    echo "No argument, while argumen has been expected"
    exit 3
  fi

  if [ -n "$setter_fn" ] && [ -z "$param_chain" ]; then
    # final seter call
    eval "set_$setter_fn"
    setter_fn=
  fi


  return 1
}

function root_required() {
  if [ -z "$RUN" ] && [ $(id -u) -ne 0 ]; then
    echo "Run it as root"
    echo "    sorry for disturbing safe realm"
    exit 0
  fi
}

function lock_mode() {
  local mode=$1

  if [ -z "${_MODE}" ]; then
    _MODE=${mode}
  elif [ "${_MODE}" != ${mode} ]; then
    echo "Syntax error."
    exit 2
  fi
}

function has_mode() {
  if [ -n "${_MODE}" ] && [ "${_MODE}" == "$1" ]; then
    # True
    return 0
  fi

  # False
  return 1
}


# parse argument loop
for opt in "$@"; do

  if ! parse "${opt}"; then
    # take next argument
    continue
  fi

  case $opt in
    --device|-d)
      lock_mode "image"
      param_chain="devmodel_name"
    ;;
    --imgboot|-i)
      lock_mode "image"

      setter_fn="flag_imgboot"
      param_chain="yes_no ?kernel_name ?initramfs_name"
    ;;
    --name|-n)
      param_chain="?container_name"
      setter_fn="create_container"
    ;;
    extstore)
      lock_mode "extstore"
    ;;
    add)
      lock_mode "extstore"

      _EXTSTORAGE_MODE="add"

      #_parse_now=""
      param_chain="extstorage ?size"
      setter_fn="validate_extstore_add"
    ;;
    eject)
      if $(has_mode "extstore"); then
        _EXTSTORAGE_MODE="eject"
      else
        echo "Wrong syntax"
        exit 2
      fi
    ;;
    command)
      lock_mode "command"
      param_chain="guestcmd"
      setter_fn="guestcmd"
    ;;
    sync)
      lock_mode "sync"

      param_chain="local_path ?remote_path"
      setter_fn="guestsync"
    ;;
    enter)
      lock_mode "enter"
    ;;
    ls)
      if $(has_mode "extstore"); then
        _EXTSTORAGE_MODE="ls"
      else
        lock_mode "list"
      fi
    ;;
    --full|-f)
      _LIST_WITH_DETAILS=1
    ;;
    --help|-h)
      print_help
      exit 0
    ;;
    init)
      lock_mode "init"
    ;;
    *)
      # probe (for image and if not exists check if name is a valid container name):
      if [ -f "$opt" ]; then
        parse_imgfile_path $opt
      else
        parse_container_name $opt
      fi
    ;;
  esac
done

# parse remaining arguments if exists
parse || true

function insert_usbstick() {
  local PATH=$1

  /usr/bin/nc -U $QEMU_MONITOR_UNIXSOCKET -q 0 <<EOF
drive_add 0 if=none,id=usbdrive1,format=raw,file=$PATH
device_add usb-storage,drive=usbdrive1,bus=usb-bus.0
EOF

  # do stuff

  #device_del usbdrive1
}

function remove_usbstick() {
# removing does not work!
  /usr/bin/nc -U $QEMU_MONITOR_UNIXSOCKET -q 0 <<EOF
drive_del usbdrive1
device_del usb-storage
EOF
}

function op_list() {
  shopt -s nullglob
  local size_h
  local details
  local cont_path

  for cont_db_path in $DB_DIR/*; do
    cont_name=$(basename $cont_db_path)
    details=
    echo -n "${cont_name}"

    if [ -f ${AWSTORE_DIR}/${cont_name}.img ]; then
      cont_path=${AWSTORE_DIR}/${cont_name}.img
    else
      cont_path=${TEMP_DIR}/${cont_name}.img
      details="Temporary   "
    fi

    if [ $_LIST_WITH_DETAILS -eq 1 ]; then
      size_h=$(first_arg $(du -h ${cont_path}))
      details="${details}${size_h}"
    fi

    if [ "$_CONTAINER_NAME" == "${cont_name}" ]; then
      echo " RUNNING ${details}"
    else
      echo "    ${details}"
    fi

  done
}

# Guest command call:
function op_gcommand() {
  local ssh_key_path=${DB_DIR}/${_CONTAINER_NAME}/${SSH_DEF_PRIV_KEY_NAME}

  $RUN ssh -p ${SSH_GUEST_PORT} -i ${ssh_key_path} root@localhost ${_GUEST_COMMAND}
}

function op_sync() {
  local ssh_key_path=${DB_DIR}/${_CONTAINER_NAME}/${SSH_DEF_PRIV_KEY_NAME}

  $RUN rsync -avz -e "ssh -p ${SSH_GUEST_PORT} -i ${ssh_key_path}" "${_RSYNC_LOCAL}" root@localhost:${_RSYNC_REMOTE}
}

function op_enter() {
  local ssh_key_path=${DB_DIR}/${_CONTAINER_NAME}/${SSH_DEF_PRIV_KEY_NAME}

  $RUN ssh -p ${SSH_GUEST_PORT} -i ${ssh_key_path} root@localhost
}


# determinate operation mode:
if [ -n "$_IMG_FILE" ]; then
  _MODE="image"
elif [ -n "$_CONTAINER_NAME" ]; then
  _MODE="container"
  # load settings
fi

case $_MODE in
  image)
    root_required
    check_environment $_MODE

    echo "Run image... $_MACHINE $_IMG_FILE $_KERNEL $_INITRAMFS"

    if [ $_PERMANENT_CONTAINER -eq 1 ]; then
      echo "Creating continer: $_CONTAINER_NAME"

      CONT_FILE=${AWSTORE_DIR}/${_CONTAINER_NAME}.img
      if [ -f ${CONT_FILE} ]; then
        echo "Container '${_CONTAINER_NAME}' already exists."
        exit 4
      fi
    else
      # running tempolary container
      CONT_FILE=$(mktemp --tmpdir=${TEMP_DIR} --suffix=-container.img)
      _CONTAINER_NAME=$(basename ${CONT_FILE} ".img")
    fi

    prepare_mmc_imgfile ${_IMG_FILE} ${CONT_FILE}
    mkdir -p ${DB_DIR}/${_CONTAINER_NAME}
    cat <<EOF > $DB_DIR/${_CONTAINER_NAME}/config.txt
# file auto-generated
container $_CONTAINER_NAME
device    $_MACHINE
kernel    $_KERNEL
initramfs $_INITRAMFS
imgboot   $_IMG_BOOT

rootimg   $_IMG_FILE
cdate     $(date)
EOF

    if [ $_IMG_BOOT -eq 1 ]; then
      # mount boot partition
      mount_boot $CONT_FILE

      _KERNEL=${BOOT_MNT_DIR}/${_KERNEL}

      if [ -f ${BOOT_MNT_DIR}/cmdline.txt ]; then
        CMDLINE_FILE_PATH=${BOOT_MNT_DIR}/cmdline.txt
      fi

      if [ -n "${_INITRAMFS}" ]; then
        _INITRAMFS=$BOOT_MNT_DIR/$_INITRAMFS
      fi
    #fi

    # installation
    #if [ $_PERMANENT_CONTAINER -eq 1 ]; then
      $RUN cp $_KERNEL ${DB_DIR}/${_CONTAINER_NAME}/
      _KERNEL=${DB_DIR}/${_CONTAINER_NAME}/$(basename ${_KERNEL})

      if [ -n "${CMDLINE_FILE_PATH}" ]; then
        $RUN cp ${CMDLINE_FILE_PATH} ${DB_DIR}/${_CONTAINER_NAME}/cmdline.txt
        CMDLINE_FILE_PATH=${DB_DIR}/${_CONTAINER_NAME}/cmdline.txt
      fi

      if [ -n "$_INITRAMFS" ]; then
        $RUN cp $_INITRAMFS $DB_DIR/$_CONTAINER_NAME/
        _INITRAMFS=$DB_DIR/$_CONTAINER_NAME/$(basename ${_INITRAMFS})
      fi
    #fi

    #if [ $_IMG_BOOT -eq 1 ]; then
      # umount boot partition
      umount_boot
    fi

    # create external storage for container:
    # prepare_usbstick ${EXTSTORE_DIR}/${_CONTAINER_NAME}-01.img 512
  ;;

  container)
    root_required
    check_environment $_MODE

    _MACHINE=$(second_arg $(cat $DB_DIR/${_CONTAINER_NAME}/config.txt | grep '^device'))
    _IMG_BOOT=$(second_arg $(cat $DB_DIR/${_CONTAINER_NAME}/config.txt | grep '^imgboot'))
    _KERNEL=$(second_arg $(cat $DB_DIR/${_CONTAINER_NAME}/config.txt | grep '^kernel'))
    _INITRAMFS=$(second_arg $(cat $DB_DIR/${_CONTAINER_NAME}/config.txt | grep '^initramfs'))

    echo "Run container... $_MACHINE $_IMG_FILE $_KERNEL $_INITRAMFS"

    _KERNEL=$DB_DIR/${_CONTAINER_NAME}/$_KERNEL

    if [ -n "$_INITRAMFS" ]; then
      _INITRAMFS=$DB_DIR/${_CONTAINER_NAME}/$_INITRAMFS
    fi

    if [ -f "${DB_DIR}/${_CONTAINER_NAME}/cmdline.txt" ]; then
      CMDLINE_FILE_PATH=${DB_DIR}/${_CONTAINER_NAME}/cmdline.txt
    fi

    CONT_FILE=${AWSTORE_DIR}/${_CONTAINER_NAME}.img

    if [ ${_IMG_BOOT} -eq 1 ]; then
      mount_boot ${CONT_FILE}

      if ! $(cmp $BOOT_MNT_DIR/$(basename ${_KERNEL}) $_KERNEL); then
        # update kernel:
        $RUN cp $BOOT_MNT_DIR/$(basename ${_KERNEL}) ${_KERNEL}
      fi

      if [ -n "${_INITRAMFS}" ] && ! $(cmp $BOOT_MNT_DIR/$(basename ${_INITRAMFS}) ${_INITRAMFS}); then
        $RUN cp $BOOT_MNT_DIR/$(basename ${_INITRAMFS}) ${_INITRAMFS}
      fi

      if [ -n "${CMDLINE_FILE_PATH}" ] && ! $(cmp ${BOOT_MNT_DIR}/cmdline.txt ${CMDLINE_FILE_PATH}); then
        $RUN cp $BOOT_MNT_DIR/cmdline.txt ${CMDLINE_FILE_PATH}
      fi

      umount_boot
    fi
  ;;
  list)
    check_environment $_MODE

    load_containersettings || true
    op_list
#    if [ $_LIST_WITH_DETAILS -eq 1 ]; then
#      ls -lh $DB_DIR
#    else
#      ls $DB_DIR
#    fi

    exit 0
  ;;
  command)
    load_containersettings
    op_gcommand

    exit 0
  ;;
  sync)
    load_containersettings
    op_sync

    exit 0
  ;;
  enter)
    load_containersettings
    op_enter

    exit 0
  ;;
  extstore)
    case $_EXTSTORAGE_MODE in
      ls)
        if [ ${_LIST_WITH_DETAILS} -eq 1 ]; then
          ls -l "${EXTSTORE_DIR}"
        else
          ls "${EXTSTORE_DIR}"
        fi
      ;;
      add)
        insert_usbstick "${_EXTSTORAGE_REF}"
      ;;
      eject)
        remove_usbstick
      ;;
    esac

    exit 0
  ;;
  init)
    root_required
    echo "Initializing $(basename $0) database and storage"

    check_environment $_MODE

    exit 0
  ;;
  *)
    # if undefined mode print help:
    print_help
    exit 2
  ;;
esac

# Test and run:

# At this point in the case of '--imgboot y' image boot partition is
# mounted and ${_KERNEL} and ${_INITRAMFS} (if defined) is a path to
# file within mounted boot partition.
# Therefore below code tests for kernel and initramfs existsnce
# regardless of '--imgboot' option.

if [ -z $RUN ] && [ ! -f ${_KERNEL} ]; then
  echo "Can't find kernel: ${_KERNEL}"
  exit 3
fi

if [ -z $RUN ] && [ -n "${_INITRAMFS}" ] && [ ! -f "${_INITRAMFS}" ]; then
  echo "Initramfs file does not exits or it's not permited to acces it."
  exit 3
fi

M_CPU=${devices_cpu[${_MACHINE}]}
M_DTB=${devices_dtb[${_MACHINE}]}

DTB_FILE=${DTB_LIB}/${M_DTB}

if [ ! -f "${DTB_FILE}" ]; then
  echo "DTB file has not been found: ${DTB_FILE}"
  exit 3
fi

#   -chardev socket,id=com0,path=/tmp/builder1.sock,server=on,wait=off \
# mount /dev/loop1p2 /mnt/dir
# cd /mnt/dir
# rm ./systemd/system/multi-user.target.wants/userconfig.service
#

# PCI required:
#   -virtfs local,path=./share,mount_tag=host0,security_model=passthrough,id=host0 \

# looks like system does not create /dev/ttyAMA0 device,
# as a result only boot messages are print, can't login
# All (Ethernet and mass storage) USB devices running at USB 1.1 speed
# slow, but works well and no rush
function run() {
  KERNEL_LINE="-kernel ${_KERNEL}"

  # add initrd if its used
  if [ -n "${_INITRAMFS}" ]; then
    KERNEL_LINE="${KERNEL_LINE} -initrd ${_INITRAMFS}"
  fi

  if [ -n "${CMDLINE_FILE_PATH}" ]; then
    KERNEL_PARAMS=$(tail -n 1 "${CMDLINE_FILE_PATH}")
  else
    # default kernel parameters
    KERNEL_PARAMS="console=tty1 console=ttyAMA0 root=/dev/mmcblk0p2 rw"
    # console=ttyAMA1

    # Set parameters
    if [ ${_NO_PART_TABLE_MODE} -eq 0 ]; then
      KERNEL_PARAMS="${KERNEL_PARAMS} root=/dev/mmcblk0p2 rw"
    else
      KERNEL_PARAMS="${KERNEL_PARAMS} modules=loop,squashfs,sd-mod,usb-storage"
    fi
  fi

  if [ -e ${LOCK_FILE} ]; then
    echo "Lock for container: "
    tail -n 1 ${LOCK_FILE}
    echo "Is it already running?"
    exit 5
  fi

  # add PID and container name
  echo $$ > ${LOCK_FILE}
  echo ${_CONTAINER_NAME} >> ${LOCK_FILE}

  #  -cpu ${M_CPU} -m 1024

  $RUN /usr/bin/qemu-system-aarch64 \
    -M ${_MACHINE} \
    -monitor unix:$QEMU_MONITOR_UNIXSOCKET,server,nowait \
    -serial pty \
    ${KERNEL_LINE} -append "${KERNEL_PARAMS}" \
    -drive id=sysdrive,if=none,format=raw,file=${CONT_FILE} \
    -device sd-card,drive=sysdrive \
    -usb \
    -device usb-kbd,bus=usb-bus.0 \
    -netdev user,id=net0,hostfwd=tcp::${SSH_GUEST_PORT}-:22 \
    -device usb-net,bus=usb-bus.0,netdev=net0 \
    -dtb ${DTB_FILE} \
    -rtc base=localtime \
    -name "$_MACHINE emulator"

    rm ${LOCK_FILE}

    # Requiers PCI:
    #     -virtfs local,id=sharedFolder,path=/tmp/aa,security_model=passthrough,mount_tag=hostshare \
    #     -drive id=imgout0,if=none,format=raw,file="${EXTSTORE_DIR}/${_CONTAINER_NAME}-01.img" \
    #      -device usb-storage,bus=usb-bus.0,drive=imgout0 \
}

run

if [ "${_MODE}" == "image" ] && [ ${_PERMANENT_CONTAINER} -eq 0 ]; then
  $RUN rm "${CONT_FILE}"
  $RUN rm -rf ${DB_DIR}/${_CONTAINER_NAME}
fi

exit 0
